Rebase (#5)
* Unbreak build on FreeBSD (#2)

* subprocess: Add missing POSIX header for BSDs

subprocess.c:345:18: warning: call to undeclared function 'kill'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  345 |         if (0 != kill(subprocess_ptr->pid, SIGKILL)) {
      |                  ^
subprocess.c:345:44: error: use of undeclared identifier 'SIGKILL'
  345 |         if (0 != kill(subprocess_ptr->pid, SIGKILL)) {
      |                                            ^
subprocess.c:1028:33: error: use of undeclared identifier 'SIGKILL'
 1028 |     BS_TEST_VERIFY_EQ(test_ptr, SIGKILL, signal_number);
      |                                 ^
subprocess.c:1046:33: error: use of undeclared identifier 'SIGABRT'
 1046 |     BS_TEST_VERIFY_EQ(test_ptr, SIGABRT, signal_number);
      |                                 ^
subprocess.c:1068:33: error: use of undeclared identifier 'SIGPIPE'
 1068 |     BS_TEST_VERIFY_EQ(test_ptr, SIGPIPE, signal_number);
      |                                 ^

* time: enable XSI extensions for gettimeofday on BSDs

time.c:41:14: warning: call to undeclared function 'gettimeofday'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   41 |     if (0 != gettimeofday(&tv, NULL)) {
      |              ^

See also https://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html

* Workflow (#4)

* Unbreak build on FreeBSD (#2)

* subprocess: Add missing POSIX header for BSDs

subprocess.c:345:18: warning: call to undeclared function 'kill'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  345 |         if (0 != kill(subprocess_ptr->pid, SIGKILL)) {
      |                  ^
subprocess.c:345:44: error: use of undeclared identifier 'SIGKILL'
  345 |         if (0 != kill(subprocess_ptr->pid, SIGKILL)) {
      |                                            ^
subprocess.c:1028:33: error: use of undeclared identifier 'SIGKILL'
 1028 |     BS_TEST_VERIFY_EQ(test_ptr, SIGKILL, signal_number);
      |                                 ^
subprocess.c:1046:33: error: use of undeclared identifier 'SIGABRT'
 1046 |     BS_TEST_VERIFY_EQ(test_ptr, SIGABRT, signal_number);
      |                                 ^
subprocess.c:1068:33: error: use of undeclared identifier 'SIGPIPE'
 1068 |     BS_TEST_VERIFY_EQ(test_ptr, SIGPIPE, signal_number);
      |                                 ^

* time: enable XSI extensions for gettimeofday on BSDs

time.c:41:14: warning: call to undeclared function 'gettimeofday'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   41 |     if (0 != gettimeofday(&tv, NULL)) {
      |              ^

See also https://pubs.opengroup.org/onlinepubs/9699919799/functions/gettimeofday.html

* Adds build-and-test workflow for libbase.

* Fixes syntax error in build-for-linux.yml

Signed-off-by: Philipp Kaeser <130065133+phkaeser@users.noreply.github.com>

* Something is off with running test, commenting out for now.

* Restricts workflow to run on main branch only. Prep before merge.

---------

Signed-off-by: Philipp Kaeser <130065133+phkaeser@users.noreply.github.com>

* Clarifies standard macro in time.c

---------

Signed-off-by: Philipp Kaeser <130065133+phkaeser@users.noreply.github.com>