subprocess: Add missing POSIX header for BSDs
subprocess.c:345:18: warning: call to undeclared function 'kill'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  345 |         if (0 != kill(subprocess_ptr->pid, SIGKILL)) {
      |                  ^
subprocess.c:345:44: error: use of undeclared identifier 'SIGKILL'
  345 |         if (0 != kill(subprocess_ptr->pid, SIGKILL)) {
      |                                            ^
subprocess.c:1028:33: error: use of undeclared identifier 'SIGKILL'
 1028 |     BS_TEST_VERIFY_EQ(test_ptr, SIGKILL, signal_number);
      |                                 ^
subprocess.c:1046:33: error: use of undeclared identifier 'SIGABRT'
 1046 |     BS_TEST_VERIFY_EQ(test_ptr, SIGABRT, signal_number);
      |                                 ^
subprocess.c:1068:33: error: use of undeclared identifier 'SIGPIPE'
 1068 |     BS_TEST_VERIFY_EQ(test_ptr, SIGPIPE, signal_number);
      |                                 ^